language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nihalsatbhai/complex-dev -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nihalsatbhai/complex-dev npm test

after_success:
  - docker build -t nihalsatbhai/multi-client ./client
  - docker build -t nihalsatbhai/multi-nginx ./nginx
  - docker build -t nihalsatbhai/multi-server ./server
  - docker build -t nihalsatbhai/multi-worker ./worker

  # Login to docker-cli. do not forget to add $DOCKER_ID and DOCKER_PASSWORD as env variables in travis-ci

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Pushing images to DockerHub

  - docker push nihalsatbhai/multi-client
  - docker push nihalsatbhai/multi-nginx
  - docker push nihalsatbhai/multi-server
  - docker push nihalsatbhai/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'Multi-Docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-935240103400'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
